"""Typings for queries generated by aiosql"""

from typing import Dict, Optional, Sequence

from asyncpg import Connection, Record

class GamesQueriesMixin:
    async def get_game_info_by_board_id(self, conn: Connection, *, board_id: str) -> Record: ...
    async def create_new_game(
        self, conn: Connection, board_id: str, click_count: int, is_finish: bool, columns: int, rows: int
    ) -> Record: ...
    async def update_game_click_count(
        self,
        conn: Connection,
        board_id: str,
        click_count: int,
    ) -> Record: ...

class CardsQueriesMixin:
    async def get_cards_by_game_id(self, conn: Connection, *, game_id: int) -> Record: ...
    async def get_card_by_position(self, conn: Connection, *, position: str, game_id: int) -> Record: ...
    async def create_new_cards(
        self, conn: Connection, cards: Dict[str, any]
    ) -> None: ...
    async def update_is_open_card(self, conn: Connection, *, position: str, game_id: int, is_open: bool) -> Record: ...


class Queries(
    GamesQueriesMixin,
    CardsQueriesMixin
): ...

queries: Queries
